### ISSUE TITLE
Multichannel files playback/panning is broken

### ISSUE THREAD

**Issue by FabriceCastel** [processing/processing-sound-archive#73] opened 2016-03-08 22:51 UTC
If I play an .mp3 or a .wav file (either one being a stereo mixdown) the sound will only ever come out of my right speaker. I know the pan() operation isn't supposed to support stereo files BUT.. this is where it gets interesting..

If I load and play a stereo audio file and then call pan(0) the sound WILL play through both speakers. In stereo.

Had a look at the source for the method and I'm.. completely confused as to WHY this works (well, it doesn't let my sketch render at all - it only plays the sound).

**Comment by wirsing** [comment] 2017-08-09 16:13
hi @FabriceCastel i'm closing this since it's a duplicate of #91 but am investigating this. thanks for the detailed report!

**Closed as completed by wirsing** 2017-08-09 16:13 UTC
