### ISSUE TITLE
Soundfile.loop() only plays once

### ISSUE THREAD

**Issue by benfry** [processing/processing-sound-archive#58] opened 2015-11-01 19:45 UTC
Reported here: https://github.com/processing/processing/issues/4081

**Comment by sjernigan** [comment] 2015-11-03 02:20
Sorry, reported in the wrong repo.  I think this is a duplicate of
https://github.com/processing/processing-sound/issues/55

**Comment by sjernigan** [comment] 2015-11-03 02:27
reproduced working with mono track, you can close this issue

**Comment by sunwangshu** [comment] 2015-11-21 20:26
I have the same problem with stereo file using processing 3.0.1. Whichever stereo file I tried the loop() didn't work. Only mono files in the examples worked fine. I tried changing the ok mono files to stereo and the problem happen as well. So I guess the reason is difference of mono and stereo like you mentioned.

**Closed as completed** 2016-09-07 01:21 UTC
