### ISSUE TITLE
Running ANY example causes JRE fatal error

### ISSUE THREAD

**Issue by hpavon** [processing/processing-sound-archive#57] opened 2015-10-27 20:40 UTC
Hi folks!

My excuses in advance if this is a dumb report, I'm quite new to Processing and Java. After spending the whole day trying to figure this out I give up and post it here.

Whenever I try to run a Sound example I have the same problem (not whith other Processing examples):
![image](https://cloud.githubusercontent.com/assets/15350007/10771815/2c5fafcc-7cf3-11e5-8f9d-de984c60d9f6.png)

Now the log file is this:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (0x20474343), pid=5136, tid=4484
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x871c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x0000000019615000):  JavaThread "Animation Thread" [_thread_in_native, id=4484, stack(0x000000001aa30000,0x000000001ab30000)]

siginfo: ExceptionCode=0x20474343, ExceptionInformation=0x00000000008eecb0 

Registers:
RAX=0x0000000000000004, RBX=0x00000000008eecb0, RCX=0x00000000008eede0, RDX=0x000000001ab2e130
RSP=0x000000001ab2dfc0, RBP=0x000000001ab2e160, RSI=0x000000001ab2e3f0, RDI=0x00000000008eecf0
R8 =0x0000000000000000, R9 =0x0000000000000000, R10=0x0000000000000000, R11=0x0000000000000000
R12=0x0000000000000000, R13=0x000000001a6a7908, R14=0x000000001ab2e5d0, R15=0x0000000019615000
RIP=0x00007ff8f28b871c, EFLAGS=0x0000000000000202

Top of Stack: (sp=0x000000001ab2dfc0)
0x000000001ab2dfc0:   00000000008ee6e0 00000000008eecb0
0x000000001ab2dfd0:   000000001ab2e3f0 00000000008eecf0
0x000000001ab2dfe0:   0000000020474343 0000000000000000
0x000000001ab2dff0:   00007ff8f28b871c 0000000000000001
0x000000001ab2e000:   00000000008eecb0 00000000008ecfc0
0x000000001ab2e010:   0000000000000001 0000000064945588
0x000000001ab2e020:   00000000008ecfc0 0000000000000001
0x000000001ab2e030:   0000000000000010 000000001ab2e5d0
0x000000001ab2e040:   000000001a6a7908 00000000008ed830
0x000000001ab2e050:   00000000000000b0 00000000ffffffff
0x000000001ab2e060:   000000001ab2e160 0000000000000000
0x000000001ab2e070:   000000001a6a7908 000000001ab2e5d0
0x000000001ab2e080:   00008b4fdcc9b5d9 000000006b9f9ff3
0x000000001ab2e090:   0000000000000000 000000006b994a6d
0x000000001ab2e0a0:   00000000000000b0 00000000ffffffff
0x000000001ab2e0b0:   00000000008eecf0 000000006b9e0fad 

Instructions: (pc=0x00007ff8f28b871c)
0x00007ff8f28b86fc:   44 3b c0 44 0f 47 c0 44 89 44 24 38 49 c1 e0 03
0x00007ff8f28b870c:   e8 33 8f ff ff 48 8d 4c 24 20 ff 15 54 0f 10 00
0x00007ff8f28b871c:   48 8b 8c 24 c0 00 00 00 48 33 cc e8 14 8d ff ff
0x00007ff8f28b872c:   48 81 c4 d8 00 00 00 c3 90 90 90 90 90 90 90 90 


Register to memory mapping:

RAX=0x0000000000000004 is an unknown value
RBX=0x00000000008eecb0 is an unknown value
RCX=0x00000000008eede0 is an unknown value
RDX=0x000000001ab2e130 is pointing into the stack for thread: 0x0000000019615000
RSP=0x000000001ab2dfc0 is pointing into the stack for thread: 0x0000000019615000
RBP=0x000000001ab2e160 is pointing into the stack for thread: 0x0000000019615000
RSI=0x000000001ab2e3f0 is pointing into the stack for thread: 0x0000000019615000
RDI=0x00000000008eecf0 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000000 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x000000001a6a7910} 'engineNew' '(II)I' in 'processing/sound/MethClaInterface'
R14=0x000000001ab2e5d0 is pointing into the stack for thread: 0x0000000019615000
R15=0x0000000019615000 is a thread


Stack: [0x000000001aa30000,0x000000001ab30000],  sp=0x000000001ab2dfc0,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [KERNELBASE.dll+0x871c]
C  [libMethClaInterface.dll+0x14a6d]
C  [libMethClaInterface.dll+0x7a3d8]
C  [libMethClaInterface.dll+0x185b]
C  [libMethClaInterface.dll+0x194a]
C  [libMethClaInterface.dll+0x23f77]
C  [libMethClaInterface.dll+0x1c0e]
C  0x000000000264dfcc

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  processing.sound.MethClaInterface.engineNew(II)I+0
j  processing.sound.Engine.<init>()V+23
j  processing.sound.Engine.<init>(Lprocessing/sound/Engine;)V+1
j  processing.sound.Engine$LazyHolder.<clinit>()V+5
v  ~StubRoutines::call_stub
j  processing.sound.Engine.start()Lprocessing/sound/Engine;+0
j  processing.sound.SoundFile.<init>(Lprocessing/core/PApplet;Ljava/lang/String;)V+68
j  Sample.setup()V+15
j  processing.core.PApplet.handleDraw()V+81
j  processing.awt.PSurfaceAWT$12.callDraw()V+7
j  processing.core.PSurfaceNone$AnimationThread.run()V+30
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0000000002533800 JavaThread "DestroyJavaVM" [_thread_blocked, id=4472, stack(0x00000000023c0000,0x00000000024c0000)]
=>0x0000000019615000 JavaThread "Animation Thread" [_thread_in_native, id=4484, stack(0x000000001aa30000,0x000000001ab30000)]
  0x00000000195ee800 JavaThread "Image Fetcher 0" daemon [_thread_blocked, id=5640, stack(0x000000001a830000,0x000000001a930000)]
  0x0000000019577800 JavaThread "AWT-EventQueue-0" [_thread_blocked, id=2376, stack(0x000000001a530000,0x000000001a630000)]
  0x000000001957f800 JavaThread "AWT-Windows" daemon [_thread_in_native, id=2028, stack(0x0000000019ee0000,0x0000000019fe0000)]
  0x000000001957f000 JavaThread "AWT-Shutdown" [_thread_blocked, id=5044, stack(0x0000000019de0000,0x0000000019ee0000)]
  0x000000001957c000 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=2032, stack(0x0000000019ce0000,0x0000000019de0000)]
  0x0000000018b50000 JavaThread "Service Thread" daemon [_thread_blocked, id=4936, stack(0x0000000018ef0000,0x0000000018ff0000)]
  0x0000000016fc1800 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=4036, stack(0x00000000189f0000,0x0000000018af0000)]
  0x0000000016fbc800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=612, stack(0x00000000188f0000,0x00000000189f0000)]
  0x0000000016fba800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=4784, stack(0x00000000187f0000,0x00000000188f0000)]
  0x0000000016fad800 JavaThread "JDWP Command Reader" daemon [_thread_in_native, id=5916, stack(0x00000000186f0000,0x00000000187f0000)]
  0x0000000016fa8800 JavaThread "JDWP Event Helper Thread" daemon [_thread_blocked, id=4864, stack(0x00000000185f0000,0x00000000186f0000)]
  0x0000000016f9a000 JavaThread "JDWP Transport Listener: dt_socket" daemon [_thread_blocked, id=3228, stack(0x00000000184f0000,0x00000000185f0000)]
  0x0000000016f91800 JavaThread "Attach Listener" daemon [_thread_blocked, id=2792, stack(0x00000000183f0000,0x00000000184f0000)]
  0x0000000016f90800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=3404, stack(0x00000000182f0000,0x00000000183f0000)]
  0x000000000262a800 JavaThread "Finalizer" daemon [_thread_blocked, id=452, stack(0x00000000181e0000,0x00000000182e0000)]
  0x0000000016f58800 JavaThread "Reference Handler" daemon [_thread_blocked, id=5412, stack(0x00000000180e0000,0x00000000181e0000)]

Other Threads:
  0x0000000016f57000 VMThread [stack: 0x0000000017fe0000,0x00000000180e0000] [id=1228]
  0x0000000018b56000 WatcherThread [stack: 0x0000000018ff0000,0x00000000190f0000] [id=2556]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 36864K, used 14341K [0x00000000d6f00000, 0x00000000d9800000, 0x0000000100000000)
  eden space 31744K, 45% used [0x00000000d6f00000,0x00000000d7d01410,0x00000000d8e00000)
  from space 5120K, 0% used [0x00000000d9300000,0x00000000d9300000,0x00000000d9800000)
  to   space 5120K, 0% used [0x00000000d8e00000,0x00000000d8e00000,0x00000000d9300000)
 ParOldGen       total 84992K, used 0K [0x0000000084c00000, 0x0000000089f00000, 0x00000000d6f00000)
  object space 84992K, 0% used [0x0000000084c00000,0x0000000084c00000,0x0000000089f00000)
 Metaspace       used 9903K, capacity 10104K, committed 10240K, reserved 1058816K
  class space    used 1078K, capacity 1154K, committed 1280K, reserved 1048576K

Card table byte_map: [0x00000000119f0000,0x0000000011dd0000] byte_map_base: 0x00000000115ca000

Marking Bits: (ParMarkBitMap*) 0x000000005aef4040
 Begin Bits: [0x0000000012470000, 0x0000000014340000)
 End Bits:   [0x0000000014340000, 0x0000000016210000)

Polling page: 0x00000000024c0000

CodeCache: size=245760Kb used=1972Kb max_used=1972Kb free=243787Kb
 bounds [0x0000000002630000, 0x00000000028a0000, 0x0000000011630000]
 total_blobs=883 nmethods=411 adapters=393
 compilation: enabled

Compilation events (10 events):
Event: 0.833 Thread 0x0000000016fc1800 nmethod 408 0x00000000028182d0 code [0x0000000002818440, 0x0000000002818650]
Event: 0.834 Thread 0x0000000016fc1800  409  s    3       java.lang.StringBuffer::append (13 bytes)
Event: 0.834 Thread 0x0000000016fc1800 nmethod 409 0x0000000002819850 code [0x00000000028199c0, 0x0000000002819ce8]
Event: 0.834 Thread 0x0000000016fc1800  410  s    3       sun.misc.PerfCounter::add (18 bytes)
Event: 0.834 Thread 0x0000000016fbc800 nmethod 402 0x0000000002817a50 code [0x0000000002817ba0, 0x00000000028180d8]
Event: 0.834 Thread 0x0000000016fc1800 nmethod 410 0x000000000281c4d0 code [0x000000000281c660, 0x000000000281ccd8]
Event: 0.836 Thread 0x0000000016fc1800  411       3       java.util.WeakHashMap::indexFor (6 bytes)
Event: 0.836 Thread 0x0000000016fc1800 nmethod 411 0x000000000281afd0 code [0x000000000281b120, 0x000000000281b250]
Event: 0.839 Thread 0x0000000016fc1800  412       3       java.lang.String::<init> (15 bytes)
Event: 0.839 Thread 0x0000000016fc1800 nmethod 412 0x000000000281cf50 code [0x000000000281d0e0, 0x000000000281d4e8]

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Internal exceptions (10 events):
Event: 0.029 Thread 0x0000000002533800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.defineClass(Ljava/lang/String;[BII)Ljava/lang/Class; name or signature does not match> (0x00000000d6f0ef08) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\sríŸÕK?
Event: 0.029 Thread 0x0000000002533800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x00000000d6f0f198) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jÐâ'cÛBâ?
Event: 0.571 Thread 0x0000000002533800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d73bbe70) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jvm.cpp, line 1382]
Event: 0.571 Thread 0x0000000002533800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d73bc028) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jvm.cpp, line 1382]
Event: 0.571 Thread 0x0000000002533800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d73bfe60) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jvm.cpp, line 1382]
Event: 0.571 Thread 0x0000000002533800 Exception <a 'java/security/PrivilegedActionException'> (0x00000000d73c0018) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jvm.cpp, line 1382]
Event: 0.575 Thread 0x0000000002533800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d73c2f60) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.627 Thread 0x0000000002533800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000d74a8548) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\methodHandles.cpp, line 1125]
Event: 0.629 Thread 0x0000000002533800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x00000000d74b6f08) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\methodHandles.cpp, line 1125]
Event: 0.704 Thread 0x0000000002533800 Exception <a 'java/io/FileNotFoundException'> (0x00000000d753add0) thrown at [C:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u51\3951\hotspot\src\share\vm\prims\jni.cpp, line 709]

Events (10 events):
Event: 0.836 Thread 0x0000000019615000 DEOPT PACKING pc=0x000000000278cff4 sp=0x000000001ab2dbd0
Event: 0.836 Thread 0x0000000019615000 DEOPT UNPACKING pc=0x000000000267787f sp=0x000000001ab2d9f0 mode 1
Event: 0.836 loading class processing/sound/MethClaInterface
Event: 0.836 loading class processing/sound/MethClaInterface done
Event: 0.836 Thread 0x0000000019615000 DEOPT PACKING pc=0x000000000278d25c sp=0x000000001ab2d300
Event: 0.836 Thread 0x0000000019615000 DEOPT UNPACKING pc=0x000000000267787f sp=0x000000001ab2d120 mode 1
Event: 0.836 Thread 0x0000000019615000 DEOPT PACKING pc=0x000000000278cff4 sp=0x000000001ab2d490
Event: 0.836 Thread 0x0000000019615000 DEOPT UNPACKING pc=0x000000000267787f sp=0x000000001ab2d2b0 mode 1
Event: 0.837 loading class java/lang/ClassLoaderHelper
Event: 0.837 loading class java/lang/ClassLoaderHelper done


Dynamic libraries:
0x00007ff6f85d0000 - 0x00007ff6f8607000     C:\Program Files\processing-3.0.1\java\bin\java.exe
0x00007ff8f5350000 - 0x00007ff8f54fc000     C:\Windows\SYSTEM32\ntdll.dll
0x00007ff8f4b30000 - 0x00007ff8f4c6e000     C:\Windows\system32\KERNEL32.DLL
0x00007ff8f28b0000 - 0x00007ff8f29c5000     C:\Windows\system32\KERNELBASE.dll
0x00007ff8f1040000 - 0x00007ff8f10ce000     C:\Windows\system32\apphelp.dll
0x00007ff8d7670000 - 0x00007ff8d76c3000     C:\Windows\AppPatch\AppPatch64\AcGenral.DLL
0x00007ff8f4900000 - 0x00007ff8f49aa000     C:\Windows\system32\msvcrt.dll
0x00007ff8f22d0000 - 0x00007ff8f22fe000     C:\Windows\SYSTEM32\SspiCli.dll
0x00007ff8f5140000 - 0x00007ff8f5194000     C:\Windows\system32\SHLWAPI.dll
0x00007ff8f49b0000 - 0x00007ff8f4b27000     C:\Windows\system32\USER32.dll
0x00007ff8f29d0000 - 0x00007ff8f2b64000     C:\Windows\system32\ole32.dll
0x00007ff8f33c0000 - 0x00007ff8f48eb000     C:\Windows\system32\SHELL32.dll
0x00007ff8f1a40000 - 0x00007ff8f1a61000     C:\Windows\SYSTEM32\USERENV.dll
0x00007ff8f4d30000 - 0x00007ff8f4dda000     C:\Windows\system32\ADVAPI32.dll
0x00007ff8ea3f0000 - 0x00007ff8ea40e000     C:\Windows\SYSTEM32\MPR.dll
0x00007ff8f5200000 - 0x00007ff8f5341000     C:\Windows\system32\RPCRT4.dll
0x00007ff8f3150000 - 0x00007ff8f31a9000     C:\Windows\SYSTEM32\sechost.dll
0x00007ff8f4eb0000 - 0x00007ff8f50c1000     C:\Windows\SYSTEM32\combase.dll
0x00007ff8f2ef0000 - 0x00007ff8f303f000     C:\Windows\system32\GDI32.dll
0x00007ff8f24a0000 - 0x00007ff8f24b5000     C:\Windows\SYSTEM32\profapi.dll
0x00007ff8f0a10000 - 0x00007ff8f0ac2000     C:\Windows\SYSTEM32\SHCORE.dll
0x00007ff8f3040000 - 0x00007ff8f3076000     C:\Windows\system32\IMM32.DLL
0x00007ff8f2d90000 - 0x00007ff8f2ee2000     C:\Windows\system32\MSCTF.dll
0x00007ff8f0590000 - 0x00007ff8f080b000     C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.18006_none_623f33d3ecbe86e8\COMCTL32.dll
0x000000005af80000 - 0x000000005b052000     C:\Program Files\processing-3.0.1\java\bin\msvcr100.dll
0x000000005a6f0000 - 0x000000005af73000     C:\Program Files\processing-3.0.1\java\bin\server\jvm.dll
0x00007ff8e6d30000 - 0x00007ff8e6d39000     C:\Windows\SYSTEM32\WSOCK32.dll
0x00007ff8e9920000 - 0x00007ff8e9942000     C:\Windows\SYSTEM32\WINMM.dll
0x00007ff8e7340000 - 0x00007ff8e734a000     C:\Windows\SYSTEM32\VERSION.dll
0x00007ff8f4de0000 - 0x00007ff8f4de7000     C:\Windows\system32\PSAPI.DLL
0x00007ff8f51a0000 - 0x00007ff8f51fa000     C:\Windows\system32\WS2_32.dll
0x00007ff8e98f0000 - 0x00007ff8e991a000     C:\Windows\SYSTEM32\WINMMBASE.dll
0x00007ff8f48f0000 - 0x00007ff8f48f9000     C:\Windows\system32\NSI.dll
0x00007ff8f2860000 - 0x00007ff8f28af000     C:\Windows\SYSTEM32\cfgmgr32.dll
0x00007ff8f1290000 - 0x00007ff8f12b8000     C:\Windows\SYSTEM32\DEVOBJ.dll
0x000000005b260000 - 0x000000005b26f000     C:\Program Files\processing-3.0.1\java\bin\verify.dll
0x000000005b230000 - 0x000000005b259000     C:\Program Files\processing-3.0.1\java\bin\java.dll
0x000000005a470000 - 0x000000005a4a5000     C:\Program Files\processing-3.0.1\java\bin\jdwp.dll
0x000000005b1c0000 - 0x000000005b1c8000     C:\Program Files\processing-3.0.1\java\bin\npt.dll
0x000000005b210000 - 0x000000005b226000     C:\Program Files\processing-3.0.1\java\bin\zip.dll
0x000000005a460000 - 0x000000005a469000     C:\Program Files\processing-3.0.1\java\bin\dt_socket.dll
0x00007ff8f1cb0000 - 0x00007ff8f1d09000     C:\Windows\system32\mswsock.dll
0x000000005a550000 - 0x000000005a6e8000     C:\Program Files\processing-3.0.1\java\bin\awt.dll
0x00007ff8f3080000 - 0x00007ff8f3141000     C:\Windows\system32\OLEAUT32.dll
0x00007ff8f1110000 - 0x00007ff8f1239000     C:\Windows\system32\uxtheme.dll
0x00007ff8f0810000 - 0x00007ff8f0831000     C:\Windows\system32\dwmapi.dll
0x00007ff8f12e0000 - 0x00007ff8f12eb000     C:\Windows\SYSTEM32\kernel.appcore.dll
0x00007ff8f2370000 - 0x00007ff8f237b000     C:\Windows\SYSTEM32\CRYPTBASE.dll
0x00007ff8f2300000 - 0x00007ff8f2363000     C:\Windows\SYSTEM32\bcryptPrimitives.dll
0x000000005a500000 - 0x000000005a547000     C:\Program Files\processing-3.0.1\java\bin\fontmanager.dll
0x0000000064940000 - 0x0000000064955000     C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64\libwinpthread-1.dll
0x0000000070440000 - 0x0000000070692000     C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64\libsndfile-1.dll
0x0000000066240000 - 0x00000000662a3000     C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64\libmpg123-0.dll
0x0000000065880000 - 0x0000000065d88000     C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64\libmethcla.dll
0x000000006b980000 - 0x000000006bad0000     C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64\libMethClaInterface.dll
0x00007ff8f4c70000 - 0x00007ff8f4d26000     C:\Windows\SYSTEM32\clbcatq.dll
0x00007ff8eecf0000 - 0x00007ff8eed60000     C:\Windows\System32\MMDevApi.dll
0x00007ff8e6d50000 - 0x00007ff8e6dce000     C:\Windows\SYSTEM32\AUDIOSES.DLL
0x00007ff8f2440000 - 0x00007ff8f2486000     C:\Windows\SYSTEM32\powrprof.dll
0x00007ff8e71b0000 - 0x00007ff8e7339000     C:\Windows\SYSTEM32\dbghelp.dll

VM Arguments:
jvm_args: -agentlib:jdwp=transport=dt_socket,address=8167,server=y,suspend=y -Djava.library.path=;C:\Program Files\processing-3.0.1\core\library;C:\Users\alumno\Documents\Processing\libraries\sound\library\windows64;C:\Program Files\processing-3.0.1\java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\nodejs;C:\Program Files\WorldPainter;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files\processing-3.0.1\java\bin;. -ea 
java_command: processing.core.PApplet --editor-location=-5,0 --external --display=1 --sketch-path=C:\Users\alumno\Documents\Processing\libraries\sound\examples\Soundfile\Sample Sample
java_class_path (initial): C:\Users\alumno\AppData\Local\Temp\Sample2456558521679656538temp;C:\Program Files\processing-3.0.1\core\library\core.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-java-src.zip;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-amd64.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-armv6hf.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-i586.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-macosx-universal.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-windows-amd64.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-windows-i586.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-linux-amd64.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-linux-armv6hf.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-linux-i586.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-macosx-universal.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-windows-amd64.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all-natives-windows-i586.jar;C:\Program Files\processing-3.0.1\core\library\jogl-all.jar;C:\Program Files\processing-3.0.1\core\library\jogl-java-src.zip;C:\Program Files\processing-3.0.1\core\library\core.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-java-src.zip;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-amd64.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-armv6hf.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-linux-i586.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-macosx-universal.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-natives-windows-amd64.jar;C:\Program Files\processing-3.0.1\core\library\gluegen-rt-nativ
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\nodejs\;C:\Program Files\WorldPainter;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Users\alumno\AppData\Roaming\npm;C:\Program Files\processing-3.0.1\java\bin
USERNAME=alumno
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel



---------------  S Y S T E M  ---------------

OS: Windows 8.1 , 64 bit Build 9600 (6.3.9600.17415)

CPU:total 4 (4 cores per cpu, 1 threads per core) family 6 model 58 stepping 9, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, clmul, erms, tsc, tscinvbit, tscinv

Memory: 4k page, physical 8073128k(5096928k free), swap 9318312k(5015192k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.51-b03) for windows-amd64 JRE (1.8.0_51-b16), built on Jun  8 2015 18:03:07 by "java_re" with MS VC++ 10.0 (VS2010)

time: Tue Oct 27 21:38:54 2015
elapsed time: 0 seconds (0d 0h 0m 0s)
```

Thanks in advance and if this is because of some stoopid thing I made, at least I hope this post is helpful to others making the same mistake  : )

Héctor Pavón

**Comment by jocousy** [comment] 2016-02-04 11:41
HI,

I have the same problem with the sound library. The log above looks similar as mine.
Can someone pls tell me what to do?

**Comment by kaoskorobase** [comment] 2016-04-05 09:49
Seems to be a duplicate of #46, please followup there.

**Closed as completed by kaoskorobase** 2016-04-05 09:49 UTC
Labels: duplicate, windows

**Comment by chazevans** [comment] 2016-04-20 19:03
I have the same error and it appears that both of these closed threads are pointing to each other. Is there any solution to this yet? Thanks.

**Comment by kaoskorobase** [comment] 2016-04-21 08:21
This issue is tracked in #46. Could you please try the latest [1.3.2 release](https://github.com/processing/processing-sound/releases/tag/v1.3.2) and follow up over there? Thanks!
